default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: designosaur_development

test:
  <<: *default
  database: designosaur_test

production:
  <<: *default
  database: designosaur_production
